/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package learningnewword;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author TUANDASE62310
 */
public class Test extends javax.swing.JFrame {

    private ArrayList<Word> words = new ArrayList();
    private int correct, incorrect;
    private int quesLan = -1, ansLan = -1;
    private Random random = new Random();
    private Word curWord = null;
    private String ques, ans;
    private boolean checked = true;
    
    public Test() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        if (words == null || words.size() == 0) {
            JOptionPane.showMessageDialog(null, "Please a"
                    + "dd words first");
            this.dispose();
        }
    }

    public Test(ArrayList<Word> words) {
        initComponents();
        this.words = new ArrayList(words);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        if (words == null || words.size() == 0) {
            JOptionPane.showMessageDialog(null, "Please ad"
                    + "d words first");
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbngQuestions = new javax.swing.ButtonGroup();
        rbngAnswers = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rbnQuesJp = new javax.swing.JRadioButton();
        rbnQuesEn = new javax.swing.JRadioButton();
        rbnQuesVi = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rbnAnsJp = new javax.swing.JRadioButton();
        rbnAnsEn = new javax.swing.JRadioButton();
        rbnAnsVi = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        lbQuestion = new javax.swing.JLabel();
        txtAnswer = new javax.swing.JTextField();
        lbAnswer = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bnCheck = new javax.swing.JButton();
        bnShowAnswer = new javax.swing.JButton();
        bnNext = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbCorrect = new javax.swing.JLabel();
        lbIncorrect = new javax.swing.JLabel();
        lbPercentage = new javax.swing.JLabel();
        lbResult = new javax.swing.JLabel();
        bnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TEST");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("TEST!!");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Choose start language:");

        rbngQuestions.add(rbnQuesJp);
        rbnQuesJp.setText("Japanese");
        rbnQuesJp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQuesJpActionPerformed(evt);
            }
        });

        rbngQuestions.add(rbnQuesEn);
        rbnQuesEn.setText("English");
        rbnQuesEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQuesEnActionPerformed(evt);
            }
        });

        rbngQuestions.add(rbnQuesVi);
        rbnQuesVi.setText("Vietnamese");
        rbnQuesVi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQuesViActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Choose answer language:");

        rbngAnswers.add(rbnAnsJp);
        rbnAnsJp.setText("Japanese");
        rbnAnsJp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnAnsJpActionPerformed(evt);
            }
        });

        rbngAnswers.add(rbnAnsEn);
        rbnAnsEn.setText("English");
        rbnAnsEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnAnsEnActionPerformed(evt);
            }
        });

        rbngAnswers.add(rbnAnsVi);
        rbnAnsVi.setText("VietNamese");
        rbnAnsVi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnAnsViActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbnAnsJp)
                        .addGap(18, 18, 18)
                        .addComponent(rbnAnsEn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbnAnsVi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbnQuesJp)
                        .addGap(18, 18, 18)
                        .addComponent(rbnQuesEn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbnQuesVi))
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rbnAnsEn, rbnAnsJp, rbnAnsVi, rbnQuesEn, rbnQuesJp, rbnQuesVi});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbnQuesJp)
                    .addComponent(rbnQuesEn)
                    .addComponent(rbnQuesVi))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbnAnsJp)
                    .addComponent(rbnAnsEn)
                    .addComponent(rbnAnsVi))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbQuestion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbQuestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQuestion.setText("Choose start and answer language!");

        txtAnswer.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        txtAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnswerActionPerformed(evt);
            }
        });

        lbAnswer.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        lbAnswer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAnswer.setText("  ");

        bnCheck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bnCheck.setText("Check");
        bnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnCheckActionPerformed(evt);
            }
        });

        bnShowAnswer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bnShowAnswer.setText("Show answer");
        bnShowAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnShowAnswerActionPerformed(evt);
            }
        });

        bnNext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bnNext.setText("Next");
        bnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bnCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bnShowAnswer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bnNext)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bnCheck, bnNext, bnShowAnswer});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnCheck)
                    .addComponent(bnShowAnswer)
                    .addComponent(bnNext))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(txtAnswer)
                .addGap(170, 170, 170))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                    .addComponent(lbAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbQuestion)
                .addGap(18, 18, 18)
                .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Correct:");

        jLabel5.setText("Incorrect:");

        jLabel6.setText("Percentage:");

        lbCorrect.setText(" ");

        lbIncorrect.setText(" ");

        lbPercentage.setText(" ");

        lbResult.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbResult.setForeground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCorrect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIncorrect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPercentage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel5, jLabel6});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbCorrect, lbIncorrect, lbPercentage});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbCorrect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbIncorrect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbPercentage))
                .addGap(18, 18, 18)
                .addComponent(lbResult, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bnBack.setText("Back");
        bnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bnBack)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_bnBackActionPerformed

    private void rbnQuesJpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQuesJpActionPerformed
        quesLan = 0;
    }//GEN-LAST:event_rbnQuesJpActionPerformed

    private void rbnQuesEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQuesEnActionPerformed
        quesLan = 1;
    }//GEN-LAST:event_rbnQuesEnActionPerformed

    private void rbnQuesViActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQuesViActionPerformed
        quesLan = 2;
    }//GEN-LAST:event_rbnQuesViActionPerformed

    private void rbnAnsJpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnAnsJpActionPerformed
        ansLan = 0;
        txtAnswer.setFont(new Font("DengXian", Font.PLAIN, 18));
    }//GEN-LAST:event_rbnAnsJpActionPerformed

    private void rbnAnsEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnAnsEnActionPerformed
        ansLan = 1;
    }//GEN-LAST:event_rbnAnsEnActionPerformed

    private void rbnAnsViActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnAnsViActionPerformed
        ansLan = 2;
        txtAnswer.setFont(new Font("Times New Roman", Font.PLAIN, 18));
    }//GEN-LAST:event_rbnAnsViActionPerformed

    private void txtAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnswerActionPerformed
        bnNextActionPerformed(null);
    }//GEN-LAST:event_txtAnswerActionPerformed

    private void bnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnNextActionPerformed
        if (quesLan == -1 || ansLan == -1) {
            JOptionPane.showMessageDialog(null, "Please choose "
                + "question language and answer language.");
            return;
        }
        if (!checked) {
            bnCheckActionPerformed(null);
            return;
        }
        checked = false;
        curWord = words.get(random.nextInt(words.size()));
        switch (quesLan) {
            case 0:
            ques = curWord.getJa();
            break;
            case 1:
            ques = curWord.getEng();
            break;
            case 2:
            ques = curWord.getVi();
            break;
        }
        switch (ansLan) {
            case 0:
            ans = curWord.getJa();
            break;
            case 1:
            ans = curWord.getEng();
            break;
            case 2:
            ans = curWord.getVi();
            break;
        }

        lbQuestion.setText(ques);
        txtAnswer.setText("");
        lbAnswer.setText("");
        txtAnswer.requestFocus();
    }//GEN-LAST:event_bnNextActionPerformed

    private void bnShowAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnShowAnswerActionPerformed
        if (quesLan == -1 || ansLan == -1) {
            JOptionPane.showMessageDialog(null, "Please choose "
                + "question language and answer language.");
            return;
        }
        if (curWord == null) {
            JOptionPane.showMessageDialog(null, "Please press "
                + "Next!");
            return;
        }
        lbAnswer.setText(ans);

        if(!checked){
            incorrect++;
            updateScore(false);
        }
        checked = true;
    }//GEN-LAST:event_bnShowAnswerActionPerformed

    private void bnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnCheckActionPerformed
        if (quesLan == -1 || ansLan == -1) {
            JOptionPane.showMessageDialog(null, "Please choose "
                + "question language and answer language.");
            return;
        }
        if (checked) {
            return;
        }
        if (curWord == null) {
            JOptionPane.showMessageDialog(null, "Please press "
                + "Next!");
            return;
        }
        String ans = txtAnswer.getText().trim();
        if (ans.equalsIgnoreCase(this.ans)) {
            correct++;
            updateScore(true);
        } else {
            incorrect++;
            updateScore(false);
            lbAnswer.setText(ans);
        }
        checked = true;
        bnShowAnswerActionPerformed(null);
    }//GEN-LAST:event_bnCheckActionPerformed

    private void updateScore(boolean ans) {
        lbCorrect.setText(Integer.toString(correct));
        lbIncorrect.setText(Integer.toString(incorrect));
        lbPercentage.setText(String.format("%.2f", 
                100.0 * correct / (correct + incorrect)) + "%");
        lbResult.setText(ans ? "Correct!!" : "Incorrect!!");
        if(ans){
            lbResult.setForeground(Color.GREEN);
        } else {
            lbResult.setForeground(Color.RED);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnBack;
    private javax.swing.JButton bnCheck;
    private javax.swing.JButton bnNext;
    private javax.swing.JButton bnShowAnswer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbAnswer;
    private javax.swing.JLabel lbCorrect;
    private javax.swing.JLabel lbIncorrect;
    private javax.swing.JLabel lbPercentage;
    private javax.swing.JLabel lbQuestion;
    private javax.swing.JLabel lbResult;
    private javax.swing.JRadioButton rbnAnsEn;
    private javax.swing.JRadioButton rbnAnsJp;
    private javax.swing.JRadioButton rbnAnsVi;
    private javax.swing.JRadioButton rbnQuesEn;
    private javax.swing.JRadioButton rbnQuesJp;
    private javax.swing.JRadioButton rbnQuesVi;
    private javax.swing.ButtonGroup rbngAnswers;
    private javax.swing.ButtonGroup rbngQuestions;
    private javax.swing.JTextField txtAnswer;
    // End of variables declaration//GEN-END:variables
}
